dags_main_orchestration = [
    "main_orchestration_angers",
    "main_orchestration_casa",
    "main_orchestration_cdc",
    "main_orchestration_cea",
    "main_orchestration_cese",
    "main_orchestration_grand_nancy",
    "main_orchestration_lyon",
    "main_orchestration_marseille",
    "main_orchestration_meyzieu",
    "main_orchestration_sytral",
    "main_orchestration_thionville",
    "main_orchestration_toulouse",
    "main_orchestration_tours",
    "main_orchestration_valbonne",
]

dags_matomo_dump_orchestration = [
    "matomo_dump_angers",
    #"matomo_dump_casa",
    "matomo_dump_cdc",
    "matomo_dump_cea",
    "matomo_dump_cese",
    "matomo_dump_grand_nancy",
    "matomo_dump_lyon",
    "matomo_dump_marseille",
    "matomo_dump_meyzieu",
    "matomo_dump_sytral",
    "matomo_dump_thionville",
    "matomo_dump_toulouse",
    "matomo_dump_tours",
    "matomo_dump_valbonne",
]