apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: airflow
  namespace: data-pprod
spec:
  interval: 15m
  chart:
    spec:
      chart: airflow
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: apache-airflow
        namespace: data-pprod
      interval: 15m
  values:
    dags:
      gitSync:
        branch: main
        enabled: true
        maxFailures: 3
        repo: https://github.com/OpenSourcePolitics/airflow-dags
        subPath: dags
        wait: 30  # Adjusted to integer type
    data:
      metadataSecretName: airflow-connection-string
    images:
      airflow:
        repository: jeanlouislamezec/airflow_test
        tag: v2
    ingress:
      web:
        annotations:
          kubernetes.io/tls-acme: "true"
        enabled: true
        hosts:
          - pprod.airflow.k8s.osp.cat
        tls:
          enabled: true
          secretName: pprod-airflow-tls
    postgresql:
      enabled: false
    triggerer:
      persistence:
        size: 10Gi
    workers:
      persistence:
        size: 10Gi
