metabase_generic_dashboard_data = {
    "angers" : {"collection_name": "Angers", "database_id": 4, "language": "fr"},
    "arcueil": {"collection_name": "Arcueil", "database_id": 205, "language": "fr"},
    "bagneux": {"collection_name": "Bagneux", "database_id": 206, "language": "fr"},
    "cachan": {"collection_name": "Cachan", "database_id": 213, "language": "fr"},
    "casa": {"collection_name": "CASA", "database_id": 59, "language": "fr"},
    "cdc": {"collection_name": "Cour des Comptes", "database_id": 56, "language": "fr"},
    "cea": {"collection_name": "C€A", "database_id": 39, "language": "fr"},
    "cese": {"collection_name": "CESE", "database_id": 129, "language": "fr"},
    "chambery": {"collection_name": "Chambéry", "database_id": 208, "language": "fr"},
    "colombes": {"collection_name": "Colombes", "database_id": 30, "language": "fr"},
    "cultuur_connect": {"collection_name": "Cultuurconnect", "database_id": 210, "language": "nl"},
    "decidim_0_29_multilang": {"collection_name": "Démo", "database_id": 218, "language": "fr"},
    "grand_nancy": {"collection_name": "Grand Nancy", "database_id": 170, "language": "fr"},
    "lyon": {"collection_name": "Lyon", "database_id": 73, "language": "fr"},
    "loire_atlantique": {"collection_name": "Loire-Atlantique", "database_id": 47, "language": "fr"},
    "malakoff": {"collection_name": "Malakoff", "database_id": 207, "language": "fr"},
    "marseille": {"collection_name": "Marseille", "database_id": 165, "language": "fr"},
    "mel":{"collection_name": "MEL", "database_id": 214, "language": "fr"},
    "montpellier": {"collection_name": "Métropole de Montpellier", "database_id": 163, "language": "fr"},
    "meyzieu": {"collection_name": "Meyzieu", "database_id": 166, "language": "fr"},
    "nanterre": {"collection_name": "Nanterre", "database_id": 211, "language": "fr"},
    "nets4dem": {"collection_name": "Nets4Dem", "database_id": 212, "language": "en"},
    "nice": {"collection_name": "Nice", "database_id": 251, "language": "fr"},
    "plaine_commune": {"collection_name": "Plaine Commune", "database_id": 216, "language": "fr"},
    "ps_belge": {"collection_name": "PS Belge", "database_id": 217, "language": "fr"},
    "real_deal": {"collection_name": "Real Deal", "database_id": 172, "language": "en"},
    "sytral": {"collection_name": "Sytral", "database_id": 33, "language": "fr"},
    "thionville": {"collection_name": "Thionville", "database_id": 122, "language": "fr"},
    "toulouse": {"collection_name": "Toulouse", "database_id": 61, "language": "fr"},
    "tours": {"collection_name": "Tours", "database_id": 65, "language": "fr"},
    "valbonne": {"collection_name": "Valbonne", "database_id": 126, "language": "fr"},
    "villeurbanne": {"collection_name": "Villeurbanne", "database_id": 209, "language": "fr"},
    }