---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: airflow
  namespace: data-prod
spec:
  ignore: "\n\t\t# exclude all\n\t\t/*\n\t\t# include prod directory\n\t\t!/prod\n\t\t"
  interval: 10m0s
  ref:
    branch: main
  url: https://github.com/OpenSourcePolitics/airflow-orchestration
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: airflow
  namespace: data-prod
spec:
  prune: false
  interval: 10m0s
  path: ./prod
  sourceRef:
    kind: GitRepository
    name: airflow
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: apache-airflow
  namespace: data-prod
spec:
  interval: 24h
  url: https://airflow.apache.org
  timeout: 3m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: airflow
  namespace: data-prod
spec:
  interval: 15m
  chart:
    spec:
      chart: airflow
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: apache-airflow
        namespace: data-prod
      interval: 15m
  values:
    createUserJob:
      useHelmHooks: false
      applyCustomEnv: false
    migrateDatabaseJob:
      useHelmHooks: false
      applyCustomEnv: false
    dags:
      gitSync:
        enabled: true
        repo: https://github.com/OpenSourcePolitics/airflow-orchestration
        branch: main
        subPath: dags
        rev: "refs/tags/dags-v1.3.10"
        wait: 300
        maxFailures: 3
    images:
      airflow:
        repository: rg.fr-par.scw.cloud/airflow-orchestration/airflow
        tag: refs-tags-airflow-v1.1.5
    ingress:
      web:
        annotations:
          kubernetes.io/tls-acme: "true"
        enabled: true
        hosts:
        - airflow.k8s.osp.cat
        tls:
          enabled: true
          secretName: airflow-tls
    webserver:
      resources:
        limits:
          memory: 1.25Gi
        requests:
          cpu: 1000m
          memory: 1.25Gi
    workers:
      persistence:
        size: 10Gi
    triggerer:
      persistence:
        size: 10Gi
    postgresql:
      enabled: false
    data:
      metadataSecretName: airflow-connection-string
